### ISSUE TITLE
Nullable type from mappings

### ISSUE THREAD

**Issue by ayedo** [ntrrgc/ts-generator#12]
Hi!

First of all, thanks for your great work :)

I have created a type mapping from UUID to 'string', which does seem to work. My problem is that if the UUID is nullable in kotlin, the typescript type is not generated as such.

Is this supposed to be liket that?

**Comment by ntrrgc** [comment]
Good catch, that's indeed a bug.

**Comment by ntrrgc** [comment]
OK, turns out this is a bug that was already fixed before by https://github.com/ntrrgc/ts-generator/pull/7

My local repo was slightly outdated so it didn't have the fix, which I ended up independently committing again...

Anyway, it was fixed in master already, but this has made me notice it's time for a release; this is an important bug.

**Comment by ntrrgc** [comment]
Fix released as part of ts-generator:1.1.1.
