### ISSUE TITLE
Propose an option to generate Optionals Instead of Nullables

### ISSUE THREAD

**Issue by geowarin** [ntrrgc/ts-generator#3]
Hello and thanks for this project.

I'd like to propose that nullable kotlin types generate `T | undefined` instead of `T | null`.

As you certainly know, javascript has two bottom types: `null` and `undefined`.
In Typescript they both have a slightly different meaning.

A type `T | null` is sometimes called Nullable (`type Nullable<T> = T | null`).
When you turn on strict null checks, typescript will force you to deal with the null value before deferencing them.

A type `T | undefined` is sometimes called Optional (`type Optional<T> = T | undefined`).
It also has a special syntax with a question mark (`field?: T`).

The main difference between those types is highlighted in the following snippet:

```ts
class NullablePerson {
  lastName: string | null
}
class OptionalPerson {
  lastName?: string
}

const p1: NullablePerson = {}; // does not compile
const p2: NullablePerson = {lastName: null}; // compiles

const p3: OptionalPerson = {}; // compiles
const p4: OptionalPerson = {lastName: null}; // does not compile
const p5: OptionalPerson = {lastName: undefined}; // compiles
```

When I consume a REST API, there are two cases:

1. I receive data from the server (GET)

In that case, both Optional and nullable will force me to check before deferrencing nullable values.
There is no difference between the two approaches.

2. I send data to the server (POST, PUT, PATCH)

In this case, I probably should not bother sending null fields.
I would rather have `Optional`s

## Jackson

Jackson has [a feature](https://fasterxml.github.io/jackson-annotations/javadoc/2.0.0/com/fasterxml/jackson/annotation/JsonInclude.Include.html#NON_NULL) that prevents null from being serialized.

## Ts-lint

Ts-lint has [a rule](https://palantir.github.io/tslint/rules/no-null-keyword/) that enforces the use of `undefined` instead of `null`.

Also relevant:

[Article - Null is bad](https://basarat.gitbooks.io/typescript/docs/tips/null.html)

What do you think? I could open a PR if you wish.

**Comment by geowarin** [comment]
Finally, most libraries in definitely-typed seem to embrace optionals instead of nullables which makes the use of nulls awkward.

**Comment by ntrrgc** [comment]
There are different opinions.

JavaScript as a language may have been better off with a single void type, but reality is that right now there are two, with slightly different semantics and different people will choose either of them; I don't expect that to change any soon.

Personally, I tend to use more `null` than `undefined` because it's more explicit, even if it requires a bit more of typing in your TypeScript code or very few more bytes in your REST response.

For instance, if you are a frontend developer debugging the responses sent from your backend, you'd be grateful to know there is an `avatar` field even if it's `null` in that concrete response. Yes, you could also look at the documentation or type definition you hopefully have updated, but it's great to have a second guarantee. Otherwise you can't be sure that field exists unless you look at the server code or force it not to be undefined. (There is no `undefined` in a JSON serialized object, rather `undefined` in JSON is the abscence of the property.)

On the TypeScript side, the fact that a field can be null does not mean that I necessarily always want it to be so by default if it's not specified. Often I want to make sure the user actually intended to use null instead of it being an unnoticed default. I use TypeScript to ensure the correctness of my code, not to save typing, after all. And actually I have avoided quite a few bugs thanks to this when doing refactors where I add to an existing interface a new field that happens to be nullable. Doing so triggers errors in the places where it needs to be specified, rather than leaving all of them with a default undefined value which may or may not be correct.

Regardless of your pick on the null vs undefined issue, `ts-generator` job is not to pick sides, but to represent whatever your server is sending. I have added a new `voidType` parameter to the `TypeScriptGenerator` constructor that you can use to choose either `null` or `undefined`.

**Comment by geowarin** [comment]
@ntrrgc Thanks for your detailed answer, it gives me a lot to think about.

And thank you so much for taking the time to update the library.

You work is awesome 🥇
